stages:
    - build
    - test
    - push
    - deploy

build_job:
    stage: build
    script:
        - echo "This build id done using command <docker build -t tag . >"         

test_job:
    stage: test
    script:
        - echo "This is testing of our docker build "                   

push_job:
    stage: push
    script: 
        - echo "This"
        - echo "is pushing to docker hub "

deploy_job:
    stage: deploy
    script:
        - echo "This"
        - echo "is deploying to EC2 instance"
